### ISSUE TITLE
Нарушение ответсвенности

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#10]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/SeveralFiles.cpp#L32

Из названия и деталей реализации ясно что сфера ответственности метода - чтение из файловой системы. Ввод-вывод не его ответсвенность. Если ты хочешь сообщить пользователю что-то о результатах, то верни эту информацию из метода. Возращать следует именно информацию, а не форматированую строку в которую уже встроенна информация. Это поможет лего реализовать перевод или изменить способ извещения пользователя о деталях работы системы. Вернуть из метода информацию можешь например с помощью std::pair или std::tuple или если информация разнародная или ее много, то следует создать структуру для этого

**Comment by Jok101r** [comment]
эти два класса делают "связку" (пару), но как это поможет мне при вызове? (По поводу метода я понял как сделать, но заинтересовала твоя идея

**Comment by sogimu** [comment]
> эти два класса делают "связку" (пару), но как это поможет мне при вызове? (По поводу метода я понял как сделать, но заинтересовала твоя идея

Пример:
```c++
std::pair<double, bool> divide(double a, double b)
{
    std::pair<double, bool> result {0, false};
    if (b != 0)
    {
        result = std::pair<double, bool> {a / b, true};
    }
    return result;
}

auto divideResult = divide(10.0, 15.0);
if (divideResult.second)
{
    std::cout << "Successfuly divided " << divideResult.first << std::endl;
}
else
{
    std::cout << "Something wrong" << std::endl;
}
```

Тут функция divide возращает не только результат, а и состояние успешности. Код вызывающий divide сам решает как реагировать, на то что произошло в ходе divide. Сейчас он выводит на консоль сообщение, а если завтра нужно будет сделать всплывающие сообщение, то код divide не нужно будет править, а значит ты не сможешь ошибиться. В этом случае код divide становится менее изменчивым и его можно, например, вынести в отдельную библиотеку и т.д.

В твоем случае ты бы мог возращать std::pair<bool, uint>. Вызывающая сторона могла бы узнать получилось или нет и если получилось, то с каким кол-вом файлов. Если ей будет нужно она выведет на консоль число файлов. В этом случае метод load окажется неизменен изменению способа ввода-вывода в программе

**Comment by Jok101r** [comment]
это гениально-_-

**Comment by sogimu** [comment]
Ну если тебе акутально сообщить вызывающему коду, что-то что скорее всего будет отображаться пользователю, то дай методу сделать свое дело и просто верни наружу

**Comment by Jok101r** [comment]
Другими словами, просто данный распределить задачи (зоны отвественности) и переложить (возложить) их на метод

**Comment by sogimu** [comment]
ага
