### ISSUE TITLE
Код не из этого класса

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#11]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/SeveralFiles.cpp#L55

Весь этот код знает о существовании Tar, хотя класс имеет название SeveralFiles. Класс должен оставаться работоспособным и не протеворечивым с любыми файлами. Например можешь спрашивать себя актуален ли этот код также для нескольих файлов изображений или фильмов.

**Comment by Jok101r** [comment]
Ну здесь такая же ошибка, как и в классе File. Но если в классе файл все понятно. То тут мне же нужно разбирать вектор на составляющие (метаданные+сам файл), кто тогда должен выполнять такую функцию? и что вообще должен выполнять тогда метод SeveralFile::save ?

**Comment by sogimu** [comment]
> что вообще должен выполнять тогда метод SeveralFile::save ?
Метод должен быть простым. Перебирать все файлы и сохранять их в папку. Возможно нужно добавить перегрузку метода save принимающую путь к папке для класса File. Что-то вроде этого

```c++
for(auto &runVecSeveralFiles : m_files)
{
    runVecSeveralFiles.save(pathToDir);
}
```

**Comment by Jok101r** [comment]
Логику понял, а где мне считывать метаданные и сохранять их файл? в методе save? тогда снова образуется противоречие(

**Comment by sogimu** [comment]
> Логику понял, а где мне считывать метаданные и сохранять их в файл? в методе save? тогда снова образуется противоречие(

Почему? У тебя в SeveralFiles просто вектор экземпляров класса File. Просто вызови у каждого save

**Comment by Jok101r** [comment]
а где мне считывать метаданные, которые хранятся в векторе, а в дальнейшем  "добавлять" их в каждый файл? 

ps: при архивировании, там вектор целиком сохранялся, и никакие метаданные не нужно считывать и "добавлять" их в архив.

**Comment by sogimu** [comment]
ну это же класс SeveralFiles. Он просто абстракция над группой объектов класса File. Там где ты их создаешь там считывай метаданные
