### ISSUE TITLE
Метод всегда отвечает true, хотя сама операция добавления еще даже не выполнена

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#13]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/TarArchive.cpp#L203

**Comment by Jok101r** [comment]
Как мне сделать правильную проверку? через try catch ?  Точнее каким более наиболее подходящим способом воспользоваться

**Comment by sogimu** [comment]
Вижу два варианта:
1. Переработать класс так что бы при вызове метода происходило физическое дописывание файла в архив
2. Bool заменить на void. Вообщем отказаться от возврата результата операции

Первый вариант предпочтительнее

**Comment by Jok101r** [comment]
1. через конструктор? другими словами этот код перейдет в конструктор класса?

**Comment by sogimu** [comment]
нет, убрать bool или переработать класс

**Comment by Jok101r** [comment]
Я тогда не понимаю 
"1. Переработать класс так что бы при вызове метода происходило физическое дописывание файла в архив"

Какая идея была?

**Comment by sogimu** [comment]
bool предлогался как результат операции. Название операции это append. У тебя метод не делает реальный "append". Он просто что-то пишет в поле класса всегда отвечает true. Для такой реализации bool бесмысленен. Он всегда равен true
