### ISSUE TITLE
Слабая проверка валидности

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#3]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/File.cpp#L88

Слабая проверка. Нет проверки корректность метаданных

**Comment by Jok101r** [comment]
А как мне их проверять, если это вектор с набором char?

**Comment by sogimu** [comment]
> А как мне их проверять, если это вектор с набором char?

С m_dataFile все норм. Нужно еще проверять метаданные. Например, может быть не валидным путь к файлу или имя. Не валидным с точки зрения файловой системы. т.е. ты не сможешь сохраниться по этому пути\имени

**Comment by Jok101r** [comment]
А я же его проверяю на входе, т.е. когда получаю путь куда сохранять (или куда сохранять), мне кажется это более логичным. (получаю из GUI) или это тоже не правильно и нужно делегировать его в File ?

**Comment by sogimu** [comment]
Ага, проверять на входе конечно нужно (мусор на входе - мусор на выходе).
У тебя сейчас метод работает частично. Реализуй его полностью
