### ISSUE TITLE
Копирование метаданных не через оператор

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#5]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/File.cpp#L32

Представление, код настройки и копирование методанных следует описать в рамках структуры Field_name. Для копирования нужно добавить оператор копирования

**Comment by Jok101r** [comment]
А в каком классе нужно реализовать оператор копирования?

**Comment by sogimu** [comment]
Field_name (Metadata)
