### ISSUE TITLE
Можно использовать более короткий include guard

### ISSUE THREAD

**Issue by sogimu** [Jok101r/Tar_prog#8]
https://github.com/Jok101r/Tar_prog/blob/96c037d38fea58ebdbb3f1de18e4b14d51b2673d/SeveralFiles.h#L5

Ты использешь современный стандарт C++. Тебе доступено использование #pragma once

**Comment by Jok101r** [comment]
Этот код создается автоматически, при создании файлов. Здесь как раз у меняясь вопросы, так как я плохо понимаю, как работает директива препроцессора.((

**Comment by sogimu** [comment]
а ну тут все просто. До C++11 были только include guard-ы в формате:
#ifndef FILE_NAME_H
#define FILE_NAME_H
// твой код в файле
#endif //FILE_NAME_H

С C++11 можно писать в формате:

#pragma once
// твой код в файле

Второй вариант короче и нельзя ошибится с #endif.

https://ru.wikipedia.org/wiki/Include_guard

**Comment by sogimu** [comment]
Ты можешь попытаться настроить clion на второй формат или править файл сам после создания
